services:
  front-end-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_VERSION=20.14.0
      - NODE_ENV=development
    command: ["npm", "run", "dev"]