version: '3'
services:
  front-end-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - .:/app  # Gắn thư mục hiện tại (chứa mã nguồn) vào thư mục /app trong container
      - /app/node_modules  # Tránh ghi đè thư mục node_modules trong container
    environment:
      - NODE_VERSION=20.14.0  # Biến môi trường cho ARG trong Dockerfile
    command: ["npm", "run", "dev"]